version: "3.8"  # optional, you can remove this warning

services:
  web:
    image: nithzp/check-in-app:latest
    container_name: check-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite_data:/app/database_storage
    environment:
      - NODE_ENV=development

volumes:
  sqlite_data:
